[project]
name = "toyllm"
version = "0.1.0"
description = ""
authors = [
    {name = "henryzhuhr",email = "henry.zhuhr@icloud.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.10.0",
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "langchain-ollama>=0.2.3",
    "langgraph>=0.3.10",
]
